version: '3'
services:
  app:
    container_name: visao
    restart: always
    build: .
    environment:
      CMD_Python: python3
    ports:
      - ${PORT_DOCKER}:${API_PORT}
    volumes:
      - .:/user/src/app
      - /user/src/app/node_modules