version: '3'
services:
  app:
    network_mode: host
    container_name: visao
    restart: always
    build: .
    ports:
      - ${PORT_DOCKER}:${PORT}
    volumes:
      - .:/user/src/app
      - /user/src/app/node_modules